"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable, Coroutine
from typing import Generic
from fastcs.tracer import Tracer
from fastcs.util import Controller_T

MethodCallback = Callable[..., Coroutine[None, None, None]]
class Method(Generic[Controller_T], Tracer):
    """Generic base class for all FastCS Controller methods."""
    def __init__(self, fn: MethodCallback, *, group: str | None = ...) -> None:
        ...
    
    @property
    def return_type(self): # -> Any:
        ...
    
    @property
    def parameters(self): # -> MappingProxyType[str, Parameter]:
        ...
    
    @property
    def docstring(self): # -> str | None:
        ...
    
    @property
    def fn(self): # -> MethodCallback:
        ...
    
    @property
    def group(self): # -> str | None:
        ...
    
