"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable, Coroutine
from typing import TYPE_CHECKING
from fastcs.methods.method import Controller_T, Method
from fastcs.controllers import BaseController

if TYPE_CHECKING:
    ...
UnboundScanCallback = Callable[[Controller_T], Coroutine[None, None, None]]
ScanCallback = Callable[[], Coroutine[None, None, None]]
class Scan(Method["BaseController"]):
    """A `Controller` `Method` that will be called periodically in the background.

    This class contains a function that is bound to a specific `Controller` instance and
    is callable outside of the class context, without an explicit `self` parameter.
    Calling an instance of this class will call the bound `Controller` method.
    """
    def __init__(self, fn: ScanCallback, period: float) -> None:
        ...
    
    @property
    def period(self): # -> float:
        ...
    
    async def __call__(self): # -> None:
        ...
    
    @property
    def fn(self) -> ScanCallback:
        ...
    


class UnboundScan(Method[Controller_T]):
    """A wrapper of an unbound `Controller` method to be bound into a `Scan`.

    This generic class stores an unbound `Controller` method - effectively a function
    that takes an instance of a specific `Controller` type (`Controller_T`). Instances
    of this class can be added at `Controller` definition, either manually or with use
    of the `scan` wrapper, to register the method to be included in the API of the
    `Controller`. When the `Controller` is instantiated, these instances will be bound
    to the instance, creating a `Scan` instance.
    """
    def __init__(self, fn: UnboundScanCallback[Controller_T], period: float) -> None:
        ...
    
    @property
    def period(self): # -> float:
        ...
    
    def bind(self, controller: Controller_T) -> Scan:
        ...
    


def scan(period: float) -> Callable[[UnboundScanCallback[Controller_T]], UnboundScanCallback[Controller_T]]:
    """Decorator to register a `Controller` method as a `Scan`

    The `Scan` method will be called periodically in the background.
    """
    ...
