"""
This type stub file was generated by pyright.
"""

from fastcs.controller_api import ControllerAPI
from .options import EpicsDocsOptions

class EpicsDocs:
    """For creating docs in the EPICS transports."""
    def __init__(self, controller_apis: ControllerAPI) -> None:
        ...
    
    def create_docs(self, options: EpicsDocsOptions | None = ...) -> None:
        ...
    
