"""
This type stub file was generated by pyright.
"""

from pvi.device import Tree
from fastcs.controller_api import ControllerAPI
from .options import EpicsGUIOptions

class EpicsGUI:
    """For creating gui in the EPICS transports."""
    def __init__(self, controller_api: ControllerAPI, pv_prefix: str) -> None:
        ...
    
    def create_gui(self, options: EpicsGUIOptions | None = ...) -> None:
        ...
    
    def extract_api_components(self, controller_api: ControllerAPI) -> Tree:
        ...
    


class PvaEpicsGUI(EpicsGUI):
    """For creating gui in the PVA EPICS transport."""
    ...
