"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from enum import Enum
from pathlib import Path

@dataclass
class EpicsDocsOptions:
    """Docs options for EPICS."""
    path: Path = ...
    depth: int | None = ...


class EpicsGUIFormat(Enum):
    """The format of an EPICS GUI."""
    bob = ...
    edl = ...


@dataclass
class EpicsGUIOptions:
    """Epics GUI options for use in both CA and PVA transports."""
    output_path: Path = ...
    file_format: EpicsGUIFormat = ...
    title: str = ...


@dataclass
class EpicsIOCOptions:
    """Epics IOC options for use in both CA and PVA transports."""
    pv_prefix: str = ...
