"""
This type stub file was generated by pyright.
"""

import asyncio
from fastcs.controller_api import ControllerAPI
from fastcs.transport.adapter import TransportAdapter
from .options import TangoOptions

class TangoTransport(TransportAdapter):
    """Tango transport."""
    def __init__(self, controller_api: ControllerAPI, loop: asyncio.AbstractEventLoop, options: TangoOptions | None = ...) -> None:
        ...
    
    @property
    def options(self) -> TangoOptions:
        ...
    
    def create_docs(self) -> None:
        ...
    
    def create_gui(self) -> None:
        ...
    
    async def serve(self) -> None:
        ...
    
