"""
This type stub file was generated by pyright.
"""

import asyncio
from fastcs.controller_api import ControllerAPI
from .options import TangoDSROptions

class TangoDSR:
    """For controlling a controller with tango.

    Avoid running directly, instead use `fastcs.launch.FastCS`.
    """
    def __init__(self, controller_api: ControllerAPI, loop: asyncio.AbstractEventLoop) -> None:
        ...
    
    def run(self, options: TangoDSROptions | None = ...) -> None:
        ...
    


def register_dev(dev_name: str, dev_class: str, dsr_instance: str) -> None:
    """Register a device instance in the tango server."""
    ...
