"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass

@dataclass
class TangoDSROptions:
    dev_name: str = ...
    dsr_instance: str = ...
    debug: bool = ...


@dataclass
class TangoOptions:
    """Options for the Tango transport."""
    dsr: TangoDSROptions = ...
