"""
This type stub file was generated by pyright.
"""

from typing import Any
from fastcs.attributes import Attribute
from fastcs.datatypes import DataType, T

TANGO_ALLOWED_DATATYPES = ...
DATATYPE_FIELD_TO_SERVER_FIELD = ...
def get_server_metadata_from_attribute(attribute: Attribute[T]) -> dict[str, Any]:
    """Gets the metadata for a Tango field from an attribute."""
    ...

def get_server_metadata_from_datatype(datatype: DataType[T]) -> dict[str, str]:
    """Gets the metadata for a Tango field from a FastCS datatype."""
    ...

def cast_to_tango_type(datatype: DataType[T], value: T) -> object:
    """Casts a value from FastCS to tango datatype."""
    ...

def cast_from_tango_type(datatype: DataType[T], value: object) -> T:
    """Casts a value from tango to FastCS datatype."""
    ...
