"""
This type stub file was generated by pyright.
"""

from collections.abc import Sequence
from typing import TypeVar
from fastcs.attributes import AnyAttributeIO, Attribute
from fastcs.methods import Command, Scan
from fastcs.tracer import Tracer

T = TypeVar("T")
class BaseController(Tracer):
    """Base class for controllers

    Instances of this class can be loaded into FastCS to expose its Attributes to
    the transport layer, which can then perform a specific function such as generating a
    UI or creating parameters for a control system.

    This class is public for type hinting purposes, but should not be inherited to
    implement device drivers. Use either ``Controller`` or ``ControllerVector`` instead.

    """
    root_attribute: Attribute | None = ...
    description: str | None = ...
    def __init__(self, path: list[str] | None = ..., description: str | None = ..., ios: Sequence[AnyAttributeIO] | None = ...) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __setattr__(self, name, value): # -> None:
        ...
    
    async def initialise(self): # -> None:
        """Hook for subclasses to dynamically add attributes before building the API"""
        ...
    
    def post_initialise(self): # -> None:
        """Hook to call after all attributes added, before serving the application"""
        ...
    
    @property
    def path(self) -> list[str]:
        """Path prefix of attributes, recursively including parent Controllers."""
        ...
    
    def set_path(self, path: list[str]): # -> None:
        ...
    
    def add_attribute(self, name, attr: Attribute): # -> None:
        ...
    
    @property
    def attributes(self) -> dict[str, Attribute]:
        ...
    
    def add_sub_controller(self, name: str, sub_controller: BaseController): # -> None:
        ...
    
    @property
    def sub_controllers(self) -> dict[str, BaseController]:
        ...
    
    def add_command(self, name: str, command: Command): # -> None:
        ...
    
    @property
    def command_methods(self) -> dict[str, Command]:
        ...
    
    def add_scan(self, name: str, scan: Scan): # -> None:
        ...
    
    @property
    def scan_methods(self) -> dict[str, Scan]:
        ...
    
