"""
This type stub file was generated by pyright.
"""

from collections.abc import Sequence
from fastcs.attributes import AnyAttributeIO
from fastcs.controllers.base_controller import BaseController
from fastcs.controllers.controller_api import ControllerAPI
from fastcs.methods import ScanCallback

class Controller(BaseController):
    """Controller containing Attributes and named sub Controllers"""
    def __init__(self, description: str | None = ..., ios: Sequence[AnyAttributeIO] | None = ...) -> None:
        ...
    
    def add_sub_controller(self, name: str, sub_controller: BaseController): # -> None:
        ...
    
    async def connect(self) -> None:
        """Hook to perform initial connection to device

        This should set ``_connected`` to ``True`` if the connection was successful to
        enable scan tasks.

        """
        ...
    
    async def reconnect(self): # -> None:
        """Hook to reconnect to device after an error

        This should set ``_connected`` to ``True`` if the connection was successful to
        enable scan tasks.

        If the connection cannot be re-established it should log an error with the
        reason. It should not raise an exception.

        """
        ...
    
    async def disconnect(self) -> None:
        """Hook to tidy up resources before stopping the application"""
        ...
    
    def create_api_and_tasks(self) -> tuple[ControllerAPI, list[ScanCallback], list[ScanCallback]]:
        """Create api for transports tasks for FastCS backend

        Creates a tuple of
            - The `ControllerAPI` for this controller
            - Initial coroutines to be run once on startup
            - Periodic coroutines to run as background tasks

        Returns:
            tuple[ControllerAPI, list[ScanCallback], list[ScanCallback]]

        """
        ...
    
