"""
This type stub file was generated by pyright.
"""

from collections.abc import Iterator, Mapping, MutableMapping, Sequence
from fastcs.attributes import AnyAttributeIO
from fastcs.controllers.base_controller import BaseController
from fastcs.util import Controller_T

class ControllerVector(MutableMapping[int, Controller_T], BaseController):
    """Controller containing Attributes and indexed sub Controllers

    The sub controllers registered with this Controller should be instances of the same
    Controller type, distinguished only by an integer index. The indexes do not need
    to be continiguous.
    """
    def __init__(self, children: Mapping[int, Controller_T], description: str | None = ..., ios: Sequence[AnyAttributeIO] | None = ...) -> None:
        ...
    
    def add_sub_controller(self, name: str, sub_controller: BaseController):
        ...
    
    def __getitem__(self, key: int) -> Controller_T:
        ...
    
    def __setitem__(self, key: int, value: Controller_T) -> None:
        ...
    
    def __delitem__(self, key: int) -> None:
        ...
    
    def __iter__(self) -> Iterator[int]:
        ...
    
    def __len__(self) -> int:
        ...
    
