"""
This type stub file was generated by pyright.
"""

from p4p.server import ServerOperation
from p4p.server.asyncio import SharedPV
from fastcs.attributes import AttrR, AttrRW, AttrW
from fastcs.methods import CommandCallback

tracer = ...
class WritePvHandler:
    def __init__(self, attr_w: AttrW | AttrRW) -> None:
        ...
    
    async def put(self, pv: SharedPV, op: ServerOperation): # -> None:
        ...
    


class CommandPvHandler:
    def __init__(self, command: CommandCallback) -> None:
        ...
    
    async def put(self, pv: SharedPV, op: ServerOperation): # -> None:
        ...
    


def make_shared_read_pv(attribute: AttrR) -> SharedPV:
    ...

def make_shared_write_pv(attribute: AttrW) -> SharedPV:
    ...

def make_command_pv(command: CommandCallback) -> SharedPV:
    ...
