"""
This type stub file was generated by pyright.
"""

from fastcs.transports.epics.gui import EpicsGUI

class PvaEpicsGUI(EpicsGUI):
    """For creating gui in the PVA EPICS transport."""
    command_value = ...
