"""
This type stub file was generated by pyright.
"""

from p4p.server import StaticProvider
from fastcs.controllers import ControllerAPI

async def parse_attributes(root_pv_prefix: str, root_controller_api: ControllerAPI) -> StaticProvider:
    """Parses `Attribute` s into p4p signals in handlers."""
    ...

class P4PIOC:
    """A P4P IOC which handles a controller"""
    def __init__(self, pv_prefix: str, controller_api: ControllerAPI) -> None:
        ...
    
    async def run(self): # -> None:
        ...
    
