"""
This type stub file was generated by pyright.
"""

from typing import Literal
from p4p.server import StaticProvider
from fastcs.controllers import ControllerAPI

AccessModeType = Literal["r", "w", "rw", "d", "x"]
def add_pvi_info(provider: StaticProvider, pv_prefix: str, controller_api: ControllerAPI, description: str | None = ...) -> None:
    """Add PVI information to given provider."""
    ...
