"""
This type stub file was generated by pyright.
"""

import asyncio
from dataclasses import dataclass
from fastcs.controllers import ControllerAPI
from fastcs.transports.epics import EpicsDocsOptions, EpicsGUIOptions, EpicsIOCOptions
from fastcs.transports.transport import Transport

@dataclass
class EpicsPVATransport(Transport):
    """PV access transport."""
    epicspva: EpicsIOCOptions = ...
    docs: EpicsDocsOptions | None = ...
    gui: EpicsGUIOptions | None = ...
    def connect(self, controller_api: ControllerAPI, loop: asyncio.AbstractEventLoop) -> None:
        ...
    
    async def serve(self) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
