"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from collections.abc import Callable
from typing import Generic, Literal
from fastcs.attributes.attribute_io_ref import AttributeIORefT
from fastcs.datatypes import DType_T, DataType
from fastcs.tracer import Tracer

AttributeAccessMode = Literal["r", "w", "rw"]
class Attribute(Generic[DType_T, AttributeIORefT], Tracer, ABC):
    """Base FastCS attribute.

    Instances of this class added to a ``Controller`` will be used by the FastCS class.
    """
    def __init__(self, datatype: DataType[DType_T], io_ref: AttributeIORefT | None = ..., group: str | None = ..., description: str | None = ...) -> None:
        ...
    
    @property
    def io_ref(self) -> AttributeIORefT:
        ...
    
    def has_io_ref(self): # -> bool:
        ...
    
    @property
    def datatype(self) -> DataType[DType_T]:
        ...
    
    @property
    def dtype(self) -> type[DType_T]:
        ...
    
    @property
    def group(self) -> str | None:
        ...
    
    @property
    def name(self) -> str:
        ...
    
    @property
    def path(self) -> list[str]:
        ...
    
    @property
    def full_name(self) -> str:
        ...
    
    @property
    @abstractmethod
    def access_mode(self) -> AttributeAccessMode:
        """The access mode of this attribute."""
        ...
    
    def add_update_datatype_callback(self, callback: Callable[[DataType[DType_T]], None]) -> None:
        ...
    
    def update_datatype(self, datatype: DataType[DType_T]) -> None:
        ...
    
    def set_name(self, name: str): # -> None:
        ...
    
    def set_path(self, path: list[str]): # -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
