"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable, Coroutine
from typing import Any
from fastcs.attributes.attribute import Attribute, AttributeAccessMode
from fastcs.attributes.attribute_io_ref import AttributeIORefT
from fastcs.attributes.util import AttrValuePredicate
from fastcs.datatypes import DType_T, DataType

AttrIOUpdateCallback = Callable[["AttrR[DType_T, Any]"], Coroutine[None, None, None]]
AttrUpdateCallback = Callable[[], Coroutine[None, None, None]]
AttrOnUpdateCallback = Callable[[DType_T], Coroutine[None, None, None]]
class AttrR(Attribute[DType_T, AttributeIORefT]):
    """A read-only ``Attribute``"""
    def __init__(self, datatype: DataType[DType_T], io_ref: AttributeIORefT | None = ..., group: str | None = ..., initial_value: DType_T | None = ..., description: str | None = ...) -> None:
        ...
    
    def get(self) -> DType_T:
        """Get the cached value of the attribute."""
        ...
    
    @property
    def access_mode(self) -> AttributeAccessMode:
        ...
    
    async def update(self, value: Any) -> None:
        """Update the value of the attibute

        This sets the cached value of the attribute presented in the API. It should
        generally only be called from an IO or a controller that is updating the value
        from some underlying source.

        Any update callbacks will be called with the new value and any update events
        with predicates satisfied by the new value will be set.

        To request a change to the setpoint of the attribute, use the ``put`` method,
        which will attempt to apply the change to the underlying source.

        Args:
            value: The new value of the attribute

        Raises:
            ValueError: If the value fails to be validated to DType_T

        """
        ...
    
    def add_on_update_callback(self, callback: AttrOnUpdateCallback[DType_T], always: bool = ...) -> None:
        """Add a callback to be called when the value of the attribute is updated

        The callback will be called with the updated value.

        """
        ...
    
    def set_update_callback(self, callback: AttrIOUpdateCallback[DType_T]): # -> None:
        """Set the callback to update the value of the attribute from the source

        The callback will be converted to an async task and called periodically.

        """
        ...
    
    def bind_update_callback(self) -> AttrUpdateCallback:
        """Bind self into the registered IO update callback"""
        ...
    
    async def wait_for_predicate(self, predicate: AttrValuePredicate[DType_T], *, timeout: float): # -> None:
        """Wait for the predicate to be satisfied when called with the current value

        Args:
            predicate: The predicate to test - a callable that takes the attribute
                value and returns True if the event should be set
            timeout: The timeout in seconds

        """
        ...
    
    async def wait_for_value(self, target_value: DType_T, *, timeout: float): # -> None:
        """Wait for self._value to equal the target value

        Args:
            target_value: The target value to wait for
            timeout: The timeout in seconds

        Raises:
            TimeoutError: If the attribute does not reach the target value within the
                timeout

        """
        ...
    
