"""
This type stub file was generated by pyright.
"""

import asyncio
from collections.abc import Callable
from dataclasses import dataclass
from typing import Generic
from fastcs.datatypes import DType_T

AttrValuePredicate = Callable[[DType_T], bool]
@dataclass(eq=False)
class PredicateEvent(Generic[DType_T]):
    """A wrapper of `asyncio.Event` that only triggers when a predicate is satisfied"""
    _predicate: AttrValuePredicate[DType_T]
    _event: asyncio.Event = ...
    def set(self, value: DType_T) -> bool:
        """Set the event if the predicate is satisfied by the value

        Returns:
            `True` if the predicate was satisfied and the event was set, else `False`

        """
        ...
    
    async def wait(self): # -> None:
        """Wait for the event to be set"""
        ...
    
    def __hash__(self) -> int:
        """Make instances unique when stored in sets"""
        ...
    
