"""
This type stub file was generated by pyright.
"""

import enum
import numpy as np
from abc import abstractmethod
from collections.abc import Sequence
from dataclasses import dataclass
from typing import Any, Generic, TypeVar

DType = (int | float | bool | str | enum.Enum | np.ndarray)
DType_T = TypeVar("DType_T", bound=DType)
@dataclass(frozen=True)
class DataType(Generic[DType_T]):
    """Generic datatype mapping to a python type, with additional metadata."""
    @property
    @abstractmethod
    def dtype(self) -> type[DType_T]:
        ...
    
    @property
    @abstractmethod
    def initial_value(self) -> DType_T:
        ...
    
    def validate(self, value: Any) -> DType_T:
        """Validate a value against the datatype.

        The base implementation is to try the cast and raise a useful error if it fails.

        Child classes can implement logic before calling ``super.validate(value)`` to
        modify the value passed in and help the cast succeed or after to perform further
        validation of the coerced type.

        Args:
            value: The value to validate

        Returns:
            The validated value

        Raises:
            ValueError: If the value cannot be coerced

        """
        ...
    
    @staticmethod
    def equal(value1: DType_T, value2: DType_T) -> bool:
        """Compare two values for equality

        Child classes can override this if the underlying type does not implement
        ``__eq__`` or to define custom logic.

        Args:
            value1: The first value to compare
            value2: The second value to compare

        Returns:
            `True` if the values are equal

        """
        ...
    
    @classmethod
    def all_equal(cls, values: Sequence[DType_T]) -> bool:
        """Compare a sequence of values for equality

        Args:
            values: Values to compare

        Returns:
            `True` if all values are equal, else `False`

        """
        ...
    
