"""
This type stub file was generated by pyright.
"""

from fastcs.controller_api import ControllerAPI
from fastcs.transport.adapter import TransportAdapter
from fastcs.transport.epics.pva.options import EpicsPVAOptions

class EpicsPVATransport(TransportAdapter):
    """PV access transport."""
    def __init__(self, controller_api: ControllerAPI, options: EpicsPVAOptions | None = ...) -> None:
        ...
    
    @property
    def options(self) -> EpicsPVAOptions:
        ...
    
    async def serve(self) -> None:
        ...
    
    def create_docs(self) -> None:
        ...
    
    def create_gui(self) -> None:
        ...
    
