"""
This type stub file was generated by pyright.
"""

from p4p.server import StaticProvider
from fastcs.controller_api import ControllerAPI

def get_pv_name(pv_prefix: str, *attribute_names: str) -> str:
    """Converts from an attribute name to a pv name."""
    ...

async def parse_attributes(root_pv_prefix: str, root_controller_api: ControllerAPI) -> list[StaticProvider]:
    """Parses `Attribute` s into p4p signals in handlers."""
    ...

class P4PIOC:
    """A P4P IOC which handles a controller.

    Avoid running directly, instead use `fastcs.launch.FastCS`.
    """
    def __init__(self, pv_prefix: str, controller_api: ControllerAPI) -> None:
        ...
    
    async def run(self): # -> None:
        ...
    
