"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from fastcs.transport.epics.options import EpicsDocsOptions, EpicsGUIOptions, EpicsIOCOptions

@dataclass
class EpicsPVAOptions:
    """Options for the EPICS PVA transport."""
    docs: EpicsDocsOptions = ...
    gui: EpicsGUIOptions = ...
    pva_ioc: EpicsIOCOptions = ...
