"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Literal
from p4p import Value
from p4p.server import StaticProvider

AccessModeType = Literal["r", "w", "rw", "d", "x"]
PviName = str
@dataclass
class _PviSignalInfo:
    """For storing a pv and it's access in pvi parsing."""
    pv: str
    access: AccessModeType
    ...


class PviDevice(dict[str, "PviDevice"]):
    """For creating a pvi structure in pva."""
    pv_prefix: str
    description: str | None
    device_signal_info: _PviSignalInfo | None
    def __init__(self, pv_prefix: str, description: str | None = ..., device_signal_info: _PviSignalInfo | None = ...) -> None:
        ...
    
    def __missing__(self, key: str) -> PviDevice:
        ...
    
    def get_recursively(self, *args: str) -> PviDevice:
        ...
    
    def make_p4p_value(self) -> Value:
        ...
    
    def make_provider(self, provider: StaticProvider | None = ...) -> StaticProvider:
        ...
    


class PviTree:
    """For storing pvi structures."""
    def __init__(self, pv_prefix: str) -> None:
        ...
    
    def add_sub_device(self, device_pv: str, description: str | None): # -> None:
        ...
    
    def add_signal(self, attribute_pv: str, access: AccessModeType): # -> None:
        ...
    
    def make_provider(self) -> StaticProvider:
        ...
    
