"""
This type stub file was generated by pyright.
"""

from fastcs.controller_api import ControllerAPI
from fastcs.transport.adapter import TransportAdapter
from .options import RestOptions

class RestTransport(TransportAdapter):
    """Rest Transport Adapter."""
    def __init__(self, controller_api: ControllerAPI, options: RestOptions | None = ...) -> None:
        ...
    
    @property
    def options(self) -> RestOptions:
        ...
    
    def create_docs(self) -> None:
        ...
    
    def create_gui(self) -> None:
        ...
    
    async def serve(self) -> None:
        ...
    
