"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass

@dataclass
class RestServerOptions:
    host: str = ...
    port: int = ...
    log_level: str = ...


@dataclass
class RestOptions:
    """Options for the Rest transport."""
    rest: RestServerOptions = ...
