"""
This type stub file was generated by pyright.
"""

from fastcs.controller_api import ControllerAPI
from .options import RestServerOptions

class RestServer:
    """A Rest Server which handles a controller.

    Avoid running directly, instead use `fastcs.launch.FastCS`.
    """
    def __init__(self, controller_api: ControllerAPI) -> None:
        ...
    
    async def serve(self, options: RestServerOptions | None): # -> None:
        ...
    
