"""
This type stub file was generated by pyright.
"""

from fastcs.datatypes import DataType, T

REST_ALLOWED_DATATYPES = ...
def convert_datatype(datatype: DataType[T]) -> type:
    """Converts a datatype to a rest serialisable type."""
    ...

def cast_to_rest_type(datatype: DataType[T], value: T) -> object:
    """Casts from an attribute value to a rest value."""
    ...

def cast_from_rest_type(datatype: DataType[T], value: object) -> T:
    """Casts from a rest value to an attribute datatype."""
    ...
