"""
This type stub file was generated by pyright.
"""

import asyncio
from typing import Any
from fastcs.controller_api import ControllerAPI
from fastcs.transport.adapter import TransportAdapter
from fastcs.transport.epics.ca.options import EpicsCAOptions

class EpicsCATransport(TransportAdapter):
    """Channel access transport."""
    def __init__(self, controller_api: ControllerAPI, loop: asyncio.AbstractEventLoop, options: EpicsCAOptions | None = ...) -> None:
        ...
    
    @property
    def options(self) -> EpicsCAOptions:
        ...
    
    def create_docs(self) -> None:
        ...
    
    def create_gui(self) -> None:
        ...
    
    async def serve(self) -> None:
        ...
    
    @property
    def context(self) -> dict[str, Any]:
        ...
    
