"""
This type stub file was generated by pyright.
"""

import asyncio
from fastcs.controller_api import ControllerAPI
from fastcs.transport.epics.options import EpicsIOCOptions

EPICS_MAX_NAME_LENGTH = ...
class EpicsCAIOC:
    """A softioc which handles a controller.

    Avoid running directly, instead use `fastcs.launch.FastCS`.
    """
    def __init__(self, pv_prefix: str, controller_api: ControllerAPI, options: EpicsIOCOptions | None = ...) -> None:
        ...
    
    def run(self, loop: asyncio.AbstractEventLoop) -> None:
        ...
    
