"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from ..options import EpicsDocsOptions, EpicsGUIOptions, EpicsIOCOptions

@dataclass
class EpicsCAOptions:
    """Options for the EPICS CA transport."""
    docs: EpicsDocsOptions = ...
    gui: EpicsGUIOptions = ...
    ca_ioc: EpicsIOCOptions = ...
