"""
This type stub file was generated by pyright.
"""

import asyncio
from dataclasses import dataclass
from typing import Any
from fastcs.controller_api import ControllerAPI
from fastcs.transport.epics.options import EpicsDocsOptions, EpicsGUIOptions, EpicsIOCOptions
from fastcs.transport.transport import Transport

logger = ...
@dataclass
class EpicsCATransport(Transport):
    """Channel access transport."""
    epicsca: EpicsIOCOptions = ...
    docs: EpicsDocsOptions | None = ...
    gui: EpicsGUIOptions | None = ...
    def connect(self, controller_api: ControllerAPI, loop: asyncio.AbstractEventLoop) -> None:
        ...
    
    async def serve(self) -> None:
        ...
    
    @property
    def context(self) -> dict[str, Any]:
        ...
    
    def __repr__(self): # -> str:
        ...
    
