"""
This type stub file was generated by pyright.
"""

import asyncio
from abc import abstractmethod
from dataclasses import dataclass
from typing import Any, ClassVar
from fastcs.controllers import ControllerAPI

@dataclass
class Transport:
    """A base class for transport's implementation
    so it can be used in FastCS."""
    subclasses: ClassVar[list[type[Transport]]] = ...
    def __init_subclass__(cls): # -> None:
        ...
    
    @classmethod
    def union(cls): # -> UnionType:
        ...
    
    @abstractmethod
    def connect(self, controller_api: ControllerAPI, loop: asyncio.AbstractEventLoop) -> None:
        ...
    
    @property
    def context(self) -> dict[str, Any]:
        ...
    
    @abstractmethod
    async def serve(self) -> None:
        ...
    
