"""
This type stub file was generated by pyright.
"""

from .ip_connection import IPConnection as IPConnection, IPConnectionSettings as IPConnectionSettings, StreamConnection as StreamConnection
from .serial_connection import SerialConnection as SerialConnection, SerialConnectionSettings as SerialConnectionSettings
