"""
This type stub file was generated by pyright.
"""

import asyncio
from dataclasses import dataclass

class DisconnectedError(Exception):
    """Raised if the ip connection is disconnected."""
    ...


@dataclass
class IPConnectionSettings:
    ip: str = ...
    port: int = ...


@dataclass
class StreamConnection:
    """For reading and writing to a stream."""
    reader: asyncio.StreamReader
    writer: asyncio.StreamWriter
    def __post_init__(self): # -> None:
        ...
    
    async def __aenter__(self): # -> Self:
        ...
    
    async def __aexit__(self, exc_type, exc_val, exc_tb): # -> None:
        ...
    
    async def send_message(self, message) -> None:
        ...
    
    async def receive_response(self) -> str:
        ...
    
    async def close(self): # -> None:
        ...
    


class IPConnection:
    """For connecting to an ip using a `StreamConnection`."""
    def __init__(self) -> None:
        ...
    
    async def connect(self, settings: IPConnectionSettings): # -> None:
        ...
    
    async def send_command(self, message) -> None:
        ...
    
    async def send_query(self, message) -> str:
        ...
    
    async def close(self): # -> None:
        ...
    
