"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass

class NotOpenedError(Exception):
    """If the serial stream is not opened."""
    ...


@dataclass
class SerialConnectionSettings:
    port: str
    baud: int = ...


class SerialConnection:
    """A serial connection."""
    def __init__(self) -> None:
        ...
    
    async def connect(self, settings: SerialConnectionSettings) -> None:
        ...
    
    async def send_command(self, message: bytes) -> None:
        ...
    
    async def send_query(self, message: bytes, response_size: int) -> bytes:
        ...
    
    async def close(self) -> None:
        ...
    
