"""
This type stub file was generated by pyright.
"""

import asyncio
from fastcs.controllers import ControllerAPI

EPICS_MAX_NAME_LENGTH = ...
tracer = ...
class EpicsCAIOC:
    """A softioc which handles a controller"""
    def __init__(self, pv_prefix: str, controller_api: ControllerAPI) -> None:
        ...
    
    def run(self, loop: asyncio.AbstractEventLoop) -> None:
        ...
    
