"""
This type stub file was generated by pyright.
"""

import asyncio
from dataclasses import dataclass
from typing import Any
from fastcs.controllers import ControllerAPI
from fastcs.transports.epics import EpicsDocsOptions, EpicsGUIOptions, EpicsIOCOptions
from fastcs.transports.transport import Transport

@dataclass
class EpicsCATransport(Transport):
    """Channel access transport."""
    epicsca: EpicsIOCOptions = ...
    docs: EpicsDocsOptions | None = ...
    gui: EpicsGUIOptions | None = ...
    def connect(self, controller_api: ControllerAPI, loop: asyncio.AbstractEventLoop) -> None:
        ...
    
    async def serve(self) -> None:
        ...
    
    @property
    def context(self) -> dict[str, Any]:
        ...
    
    def __repr__(self): # -> str:
        ...
    
