"""
This type stub file was generated by pyright.
"""

import logging
from loguru import logger as _logger
from ._graylog import GraylogEndpoint as GraylogEndpoint, GraylogEnvFields as GraylogEnvFields, GraylogStaticFields as GraylogStaticFields, parse_graylog_env_fields as parse_graylog_env_fields, parse_graylog_static_fields as parse_graylog_static_fields
from ._logging import LogLevel, Logger, _configure_logger

logger = ...
def bind_logger(logger_name: str) -> Logger:
    """Create a wrapper of the singleton fastcs logger with the given name bound

    The name will be displayed in all log messages from the returned wrapper.

    See the docstring for ``fastcs.logging.logger`` for more information.

    """
    ...

def configure_logging(level: LogLevel | None = ..., graylog_endpoint: GraylogEndpoint | None = ..., graylog_static_fields: GraylogStaticFields | None = ..., graylog_env_fields: GraylogEnvFields | None = ...): # -> None:
    """Configure FastCS logger

    This function can be called at any time to
      - Change the console log level
      - Enable/disable graylog logging

    :param level: Log level to set
    :param graylog_endpoint: Endpoint for graylog logging - '<host>:<port>'
    :param graylog_static_fields: Fields to add to graylog messages with static values
    :param graylog_env_fields: Fields to add to graylog messages from env variables

    """
    ...

class _StdLoggingInterceptHandler(logging.Handler):
    """A std logging handler to forward messages to loguru with nice formatting."""
    def emit(self, record: logging.LogRecord): # -> None:
        ...
    


def intercept_std_logger(logger_name: str): # -> None:
    """Intercept std logging messages from the given logger

    To find the correct ``logger_name`` for a message. Add a breakpoint in
    ``logging.Logger.callHandlers``, debug and run until the log message appears as
    ``record.msg``. The logger name will be in ``self.name``.

    :param logger_name: Name of the logger to intercept

    """
    ...
