"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import NewType

@dataclass
class GraylogEndpoint:
    """Server and port for a graylog instance."""
    host: str
    port: int
    @classmethod
    def parse_graylog_endpoint(cls, endpoint: str) -> GraylogEndpoint:
        ...
    


GraylogEnvFields = NewType("GraylogEnvFields", dict[str, str])
def parse_graylog_env_fields(comma_separated_fields: str) -> GraylogEnvFields:
    ...

GraylogStaticFields = NewType("GraylogStaticFields", dict[str, str])
def parse_graylog_static_fields(comma_separated_fields: str) -> GraylogStaticFields:
    ...
