"""
This type stub file was generated by pyright.
"""

from . import attributes as attributes, controller as controller, cs_methods as cs_methods, datatypes as datatypes, transport as transport
from ._version import __version__ as __version__
from .launch import FastCS as FastCS

"""Top level API.

.. data:: __version__
    :type: str

    Version number as calculated by https://github.com/pypa/setuptools_scm
"""
