"""
This type stub file was generated by pyright.
"""

import fastcs
from collections.abc import Callable
from enum import Enum
from typing import Any, Generic
from .datatypes import AttrCallback, DataType, T

ONCE = ...
class AttrMode(Enum):
    """Access mode of an ``Attribute``."""
    READ = ...
    WRITE = ...
    READ_WRITE = ...


class _BaseAttrHandler:
    async def initialise(self, controller: fastcs.controller.BaseController) -> None:
        ...
    


class AttrHandlerW(_BaseAttrHandler):
    """Protocol for setting the value of an ``Attribute``."""
    async def put(self, attr: AttrW[T], value: T) -> None:
        ...
    


class AttrHandlerR(_BaseAttrHandler):
    """Protocol for updating the cached readback value of an ``Attribute``."""
    update_period: float | None = ...
    async def update(self, attr: AttrR[T]) -> None:
        ...
    


class AttrHandlerRW(AttrHandlerR, AttrHandlerW):
    """Protocol encapsulating both ``AttrHandlerR`` and ``AttHandlerW``."""
    ...


class SimpleAttrHandler(AttrHandlerRW):
    """Handler for internal parameters"""
    async def put(self, attr: AttrW[T], value: T) -> None:
        ...
    
    async def update(self, attr: AttrR) -> None:
        ...
    


class Attribute(Generic[T]):
    """Base FastCS attribute.

    Instances of this class added to a ``Controller`` will be used by the backend.
    """
    def __init__(self, datatype: DataType[T], access_mode: AttrMode, group: str | None = ..., handler: Any = ..., description: str | None = ...) -> None:
        ...
    
    @property
    def datatype(self) -> DataType[T]:
        ...
    
    @property
    def dtype(self) -> type[T]:
        ...
    
    @property
    def access_mode(self) -> AttrMode:
        ...
    
    @property
    def group(self) -> str | None:
        ...
    
    async def initialise(self, controller: fastcs.controller.BaseController) -> None:
        ...
    
    def add_update_datatype_callback(self, callback: Callable[[DataType[T]], None]) -> None:
        ...
    
    def update_datatype(self, datatype: DataType[T]) -> None:
        ...
    


class AttrR(Attribute[T]):
    """A read-only ``Attribute``."""
    def __init__(self, datatype: DataType[T], access_mode=..., group: str | None = ..., handler: AttrHandlerR | None = ..., initial_value: T | None = ..., description: str | None = ...) -> None:
        ...
    
    def get(self) -> T:
        ...
    
    async def set(self, value: T) -> None:
        ...
    
    def add_update_callback(self, callback: AttrCallback[T]) -> None:
        ...
    
    @property
    def updater(self) -> AttrHandlerR | None:
        ...
    


class AttrW(Attribute[T]):
    """A write-only ``Attribute``."""
    def __init__(self, datatype: DataType[T], access_mode=..., group: str | None = ..., handler: AttrHandlerW | None = ..., description: str | None = ...) -> None:
        ...
    
    async def process(self, value: T) -> None:
        ...
    
    async def process_without_display_update(self, value: T) -> None:
        ...
    
    async def update_display_without_process(self, value: T) -> None:
        ...
    
    def add_process_callback(self, callback: AttrCallback[T]) -> None:
        ...
    
    def has_process_callback(self) -> bool:
        ...
    
    def add_write_display_callback(self, callback: AttrCallback[T]) -> None:
        ...
    
    @property
    def sender(self) -> AttrHandlerW | None:
        ...
    


class AttrRW(AttrR[T], AttrW[T]):
    """A read-write ``Attribute``."""
    def __init__(self, datatype: DataType[T], access_mode=..., group: str | None = ..., handler: AttrHandlerRW | None = ..., initial_value: T | None = ..., description: str | None = ...) -> None:
        ...
    
    async def process(self, value: T) -> None:
        ...
    
