"""
This type stub file was generated by pyright.
"""

import asyncio
from .controller import Controller
from .controller_api import ControllerAPI

class Backend:
    """For keeping track of tasks during FastCS serving."""
    def __init__(self, controller: Controller, loop: asyncio.AbstractEventLoop) -> None:
        ...
    
    def __del__(self): # -> None:
        ...
    
    async def serve(self): # -> None:
        ...
    


def build_controller_api(controller: Controller) -> ControllerAPI:
    """Build a `ControllerAPI` for a `BaseController` and its sub controllers"""
    ...
