"""
This type stub file was generated by pyright.
"""

from collections.abc import Iterator
from dataclasses import dataclass
from fastcs.attributes import Attribute
from fastcs.cs_methods import Command, Put, Scan

@dataclass
class ControllerAPI:
    """Attributes, bound methods and sub APIs of a `Controller` / `SubController`"""
    path: list[str] = ...
    attributes: dict[str, Attribute] = ...
    command_methods: dict[str, Command] = ...
    put_methods: dict[str, Put] = ...
    scan_methods: dict[str, Scan] = ...
    sub_apis: dict[str, ControllerAPI] = ...
    description: str | None = ...
    def walk_api(self) -> Iterator[ControllerAPI]:
        """Walk through all the nested `ControllerAPI` s of this `ControllerAPI`.

        Yields the `ControllerAPI` s from a depth-first traversal of the tree,
        including self.

        """
        ...
    
