"""
This type stub file was generated by pyright.
"""

from fastcs.attributes import Attribute

class BaseController:
    """Base class for controller."""
    attributes: dict[str, Attribute]
    description: str | None = ...
    def __init__(self, path: list[str] | None = ..., description: str | None = ...) -> None:
        ...
    
    async def initialise(self): # -> None:
        ...
    
    async def attribute_initialise(self) -> None:
        ...
    
    @property
    def path(self) -> list[str]:
        """Path prefix of attributes, recursively including parent Controllers."""
        ...
    
    def set_path(self, path: list[str]): # -> None:
        ...
    
    def register_sub_controller(self, name: str, sub_controller: SubController): # -> None:
        ...
    
    def get_sub_controllers(self) -> dict[str, SubController]:
        ...
    


class Controller(BaseController):
    """Top-level controller for a device.

    This is the primary class for implementing device support in FastCS. Instances of
    this class can be loaded into a backend to access its ``Attribute``s. The backend
    can then perform a specific function with the set of ``Attributes``, such as
    generating a UI or creating parameters for a control system.
    """
    def __init__(self, description: str | None = ...) -> None:
        ...
    
    async def connect(self) -> None:
        ...
    


class SubController(BaseController):
    """A subordinate to a ``Controller`` for managing a subset of a device.

    An instance of this class can be registered with a parent ``Controller`` to include
    it as part of a larger device.
    """
    root_attribute: Attribute | None = ...
    def __init__(self, description: str | None = ...) -> None:
        ...
    
