"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable, Coroutine
from typing import Any, Generic, TypeVar
from fastcs.controller import BaseController
from fastcs.tracer import Tracer

MethodCallback = Callable[..., Coroutine[None, None, None]]
Controller_T = TypeVar("Controller_T", bound=BaseController)
UnboundCommandCallback = Callable[[Controller_T], Coroutine[None, None, None]]
UnboundScanCallback = Callable[[Controller_T], Coroutine[None, None, None]]
UnboundPutCallback = Callable[[Controller_T, Any], Coroutine[None, None, None]]
CommandCallback = Callable[[], Coroutine[None, None, None]]
ScanCallback = Callable[[], Coroutine[None, None, None]]
PutCallback = Callable[[Any], Coroutine[None, None, None]]
method_not_bound_error = ...
class Method(Generic[Controller_T], Tracer):
    """Generic base class for all FastCS Controller methods."""
    def __init__(self, fn: MethodCallback, *, group: str | None = ...) -> None:
        ...
    
    @property
    def return_type(self): # -> Any:
        ...
    
    @property
    def parameters(self): # -> MappingProxyType[str, Parameter]:
        ...
    
    @property
    def docstring(self): # -> str | None:
        ...
    
    @property
    def fn(self): # -> MethodCallback:
        ...
    
    @property
    def group(self): # -> str | None:
        ...
    


class Command(Method[BaseController]):
    """A `Controller` `Method` that performs a single action when called.

    This class contains a function that is bound to a specific `Controller` instance and
    is callable outside of the class context, without an explicit `self` parameter.
    Calling an instance of this class will call the bound `Controller` method.
    """
    def __init__(self, fn: CommandCallback, *, group: str | None = ...) -> None:
        ...
    
    async def __call__(self): # -> None:
        ...
    


class Scan(Method[BaseController]):
    """A `Controller` `Method` that will be called periodically in the background.

    This class contains a function that is bound to a specific `Controller` instance and
    is callable outside of the class context, without an explicit `self` parameter.
    Calling an instance of this class will call the bound `Controller` method.
    """
    def __init__(self, fn: ScanCallback, period: float) -> None:
        ...
    
    @property
    def period(self): # -> float:
        ...
    
    async def __call__(self): # -> None:
        ...
    


class UnboundCommand(Method[Controller_T]):
    """A wrapper of an unbound `Controller` method to be bound into a `Command`.

    This generic class stores an unbound `Controller` method - effectively a function
    that takes an instance of a specific `Controller` type (`Controller_T`). Instances
    of this class can be added at `Controller` definition, either manually or with use
    of the `command` wrapper, to register the method to be included in the API of the
    `Controller`. When the `Controller` is instantiated, these instances will be bound
    to the instance, creating a `Command` instance.
    """
    def __init__(self, fn: UnboundCommandCallback[Controller_T], *, group: str | None = ...) -> None:
        ...
    
    def bind(self, controller: Controller_T) -> Command:
        ...
    
    def __call__(self):
        ...
    


class UnboundScan(Method[Controller_T]):
    """A wrapper of an unbound `Controller` method to be bound into a `Scan`.

    This generic class stores an unbound `Controller` method - effectively a function
    that takes an instance of a specific `Controller` type (`Controller_T`). Instances
    of this class can be added at `Controller` definition, either manually or with use
    of the `scan` wrapper, to register the method to be included in the API of the
    `Controller`. When the `Controller` is instantiated, these instances will be bound
    to the instance, creating a `Scan` instance.
    """
    def __init__(self, fn: UnboundScanCallback[Controller_T], period: float) -> None:
        ...
    
    @property
    def period(self): # -> float:
        ...
    
    def bind(self, controller: Controller_T) -> Scan:
        ...
    
    def __call__(self):
        ...
    
