"""
This type stub file was generated by pyright.
"""

import enum
import numpy as np
from abc import abstractmethod
from collections.abc import Awaitable, Callable
from dataclasses import dataclass
from functools import cached_property
from typing import Any, Generic, TypeVar
from numpy.typing import DTypeLike

T = TypeVar("T", int, float, bool, str, enum.Enum, np.ndarray, list[tuple[str, DTypeLike]])
ATTRIBUTE_TYPES: tuple[type] = ...
AttrCallback = Callable[[T], Awaitable[None]]
@dataclass(frozen=True)
class DataType(Generic[T]):
    """Generic datatype mapping to a python type, with additional metadata."""
    @property
    @abstractmethod
    def dtype(self) -> type[T]:
        ...
    
    def validate(self, value: Any) -> T:
        """Validate a value against the datatype.

        The base implementation is to try the cast and raise a useful error if it fails.

        Child classes can implement logic before calling ``super.validate(value)`` to
        modify the value passed in and help the cast succeed or after to perform further
        validation of the coerced type.

        """
        ...
    
    @property
    @abstractmethod
    def initial_value(self) -> T:
        ...
    


T_Numerical = TypeVar("T_Numerical", int, float)
@dataclass(frozen=True)
class _Numerical(DataType[T_Numerical]):
    units: str | None = ...
    min: T_Numerical | None = ...
    max: T_Numerical | None = ...
    min_alarm: T_Numerical | None = ...
    max_alarm: T_Numerical | None = ...
    def validate(self, value: T_Numerical) -> T_Numerical:
        ...
    
    @property
    def initial_value(self) -> T_Numerical:
        ...
    


@dataclass(frozen=True)
class Int(_Numerical[int]):
    """`DataType` mapping to builtin ``int``."""
    @property
    def dtype(self) -> type[int]:
        ...
    


@dataclass(frozen=True)
class Float(_Numerical[float]):
    """`DataType` mapping to builtin ``float``."""
    prec: int = ...
    @property
    def dtype(self) -> type[float]:
        ...
    
    def validate(self, value: float) -> float:
        ...
    


@dataclass(frozen=True)
class Bool(DataType[bool]):
    """`DataType` mapping to builtin ``bool``."""
    @property
    def dtype(self) -> type[bool]:
        ...
    
    @property
    def initial_value(self) -> bool:
        ...
    


@dataclass(frozen=True)
class String(DataType[str]):
    """`DataType` mapping to builtin ``str``."""
    @property
    def dtype(self) -> type[str]:
        ...
    
    @property
    def initial_value(self) -> str:
        ...
    


T_Enum = TypeVar("T_Enum", bound=enum.Enum)
@dataclass(frozen=True)
class Enum(Generic[T_Enum], DataType[T_Enum]):
    enum_cls: type[T_Enum]
    def __post_init__(self): # -> None:
        ...
    
    def index_of(self, value: T_Enum) -> int:
        ...
    
    @cached_property
    def members(self) -> list[T_Enum]:
        ...
    
    @cached_property
    def names(self) -> list[str]:
        ...
    
    @property
    def dtype(self) -> type[T_Enum]:
        ...
    
    @property
    def initial_value(self) -> T_Enum:
        ...
    


@dataclass(frozen=True)
class Waveform(DataType[np.ndarray]):
    array_dtype: DTypeLike
    shape: tuple[int, ...] = ...
    @property
    def dtype(self) -> type[np.ndarray]:
        ...
    
    @property
    def initial_value(self) -> np.ndarray:
        ...
    
    def validate(self, value: np.ndarray) -> np.ndarray:
        ...
    


@dataclass(frozen=True)
class Table(DataType[np.ndarray]):
    structured_dtype: list[tuple[str, DTypeLike]]
    @property
    def dtype(self) -> type[np.ndarray]:
        ...
    
    @property
    def initial_value(self) -> np.ndarray:
        ...
    
    def validate(self, value: np.ndarray) -> np.ndarray:
        ...
    
