"""
This type stub file was generated by pyright.
"""

from typing import Any, TypeAlias
from .controller import Controller
from .transport.epics.ca.options import EpicsCAOptions
from .transport.epics.pva.options import EpicsPVAOptions
from .transport.graphql.options import GraphQLOptions
from .transport.rest.options import RestOptions
from .transport.tango.options import TangoOptions

TransportOptions: TypeAlias = list[EpicsPVAOptions | EpicsCAOptions | TangoOptions | RestOptions | GraphQLOptions]
class FastCS:
    """For launching a controller with given transport(s)."""
    def __init__(self, controller: Controller, transport_options: TransportOptions) -> None:
        ...
    
    def create_docs(self) -> None:
        ...
    
    def create_gui(self) -> None:
        ...
    
    def run(self): # -> None:
        ...
    
    async def serve(self) -> None:
        ...
    


def launch(controller_class: type[Controller], version: str | None = ...) -> None:
    """
    Serves as an entry point for starting FastCS applications.

    By utilizing type hints in a Controller's __init__ method, this
    function provides a command-line interface to describe and gather the
    required configuration before instantiating the application.

    Args:
        controller_class (type[Controller]): The FastCS Controller to instantiate.
            It must have a type-hinted __init__ method and no more than 2 arguments.
        version (Optional[str]): The version of the FastCS Controller.
            Optional

    Raises:
        LaunchError: If the class's __init__ is not as expected

    Example of the expected Controller implementation:
        class MyController(Controller):
            def __init__(self, my_arg: MyControllerOptions) -> None:
                ...

    Typical usage:
        if __name__ == "__main__":
            launch(MyController)
    """
    ...

def get_controller_schema(target: type[Controller]) -> dict[str, Any]:
    """Gets schema for a give controller for serialisation."""
    ...
