"""
This type stub file was generated by pyright.
"""

from typing import Any

class Tracer:
    """A mixin or standalone class for conditionally logging trace events.

    This can be used for verbose logging that is disabled by default and enabled on a
    per-instance basis, with filtering based on specific key-value pairs on the event.

    Any instance of this class can enable tracing independently. Some key classes
    inherit this class, such as ``Attributes``, and some modules have their own
    ``Tracer``, such as ``fastcs.launch``. When enabled, any event logged from the
    object, or from another ``Tracer`` that uses the object as the ``topic``, will be
    logged.

    Note: The global logger level must be set to ``TRACE`` for the messages to be logged

    Example usage:
    .. code-block:: python

        controller.ramp_rate.enable_tracing()
        controller.ramp_rate.disable_tracing()
        controller.connection.enable_tracing()
        controller.connection.add_tracing_filter("query", "V?")
        controller.connection.remove_tracing_filter("query", "V?")
        controller.connection.disable_tracing()

    :param name: The name of the logger. Attached to log messages as ``logger_name``.

    """
    def __init__(self, name: str | None = ...) -> None:
        ...
    
    def log_event(self, event: str, topic: Tracer | None = ..., *args, **kwargs): # -> None:
        """Log an event only if tracing is enabled and the filter matches

        :param event: A message describing the event
        :param topic: Another `Tracer` related to this event to enable it to be logged
        :param args: Positional arguments for underlying logger
        :param kwargs: Keyword arguments for underlying logger

        """
        ...
    
    def enable_tracing(self): # -> None:
        """Enable trace logging for this object"""
        ...
    
    def disable_tracing(self): # -> None:
        """Disable trace logging for this object"""
        ...
    
    def add_tracing_filter(self, key: str, value: Any): # -> None:
        """Add a filter for trace log messages from this object

        To reduce trace messages further, a filter can be applied such that events must
        have a key with a specific value for it to be logged.

        :param key: A new or existing key to filter on
        :param value: An allowed value for the event to be logged

        """
        ...
    
    def remove_tracing_filter(self, key: str, value: Any): # -> None:
        """Remove a specific key-value pair from the filter

        :param key: An existing filter key
        :param value: The allowed value to remove

        """
        ...
    
    def clear_tracing_filters(self): # -> None:
        """Clear all filters and allow all messages to be logged (if enabled)"""
        ...
    
