"""
This type stub file was generated by pyright.
"""

from fastcs.controller import BaseController
from fastcs.datatypes import DataType

def snake_to_pascal(name: str) -> str:
    """Converts string from snake case to Pascal case.
    If string is not a valid snake case it will be returned unchanged
    """
    ...

def numpy_to_fastcs_datatype(np_type) -> DataType:
    """Converts numpy types to fastcs types for widget creation.
    Only types important for widget creation are explicitly converted
    """
    ...

def validate_hinted_attributes(controller: BaseController): # -> None:
    """Validates that type-hinted attributes exist in the controller, and are accessible
    via the dot accessor, from the attributes dictionary and with the right datatype.
    """
    ...
