"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable
from .cs_methods import Controller_T, UnboundCommand, UnboundCommandCallback, UnboundScan, UnboundScanCallback

def scan(period: float) -> Callable[[UnboundScanCallback[Controller_T]], UnboundScan[Controller_T]]:
    """Sets up a scan over the wrapped method."""
    ...

def command(*, group: str | None = ...) -> Callable[[UnboundCommandCallback[Controller_T]], UnboundCommand[Controller_T]]:
    """Decorator to tag a `Controller` method to be turned into a `Command`.

    Args:
        group: Group to display this command under in the transport layer

    """
    ...
