"""
This type stub file was generated by pyright.
"""

from fastcs.controller_api import ControllerAPI
from fastcs.transport.adapter import TransportAdapter
from .options import GraphQLOptions

class GraphQLTransport(TransportAdapter):
    """GraphQL transport."""
    def __init__(self, controller_api: ControllerAPI, options: GraphQLOptions | None = ...) -> None:
        ...
    
    @property
    def options(self) -> GraphQLOptions:
        ...
    
    def create_docs(self) -> None:
        ...
    
    def create_gui(self) -> None:
        ...
    
    async def serve(self) -> None:
        ...
    
