"""
This type stub file was generated by pyright.
"""

import strawberry
from fastcs.controller_api import ControllerAPI
from .options import GraphQLServerOptions

class GraphQLServer:
    """A GraphQL server which handles a controller.

    Avoid running directly, instead use `fastcs.launch.FastCS`.
    """
    def __init__(self, controller_api: ControllerAPI) -> None:
        ...
    
    async def serve(self, options: GraphQLServerOptions | None = ...) -> None:
        ...
    


class GraphQLAPI:
    """A Strawberry API built dynamically from a `ControllerAPI`"""
    def __init__(self, controller_api: ControllerAPI) -> None:
        ...
    
    def create_schema(self) -> strawberry.Schema:
        """Create a Strawberry Schema to load into a GraphQL application."""
        ...
    
