"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass

@dataclass
class GraphQLServerOptions:
    host: str = ...
    port: int = ...
    log_level: str = ...


@dataclass
class GraphQLOptions:
    """Options for the GraphQL transport."""
    gql: GraphQLServerOptions = ...
