"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from typing import Any

class TransportAdapter(ABC):
    """A base class for adapting a transport's implementation to
    so it can be used in FastCS."""
    @property
    @abstractmethod
    def options(self) -> Any:
        ...
    
    @abstractmethod
    async def serve(self) -> None:
        ...
    
    @abstractmethod
    def create_docs(self) -> None:
        ...
    
    @abstractmethod
    def create_gui(self) -> None:
        ...
    
    @property
    def context(self) -> dict[str, Any]:
        ...
    
